# Generated by Django 5.2.16 on 2026-07-09 20:33

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("awaiting_survey", "Awaiting survey"),
                            ("awaiting_insurer", "Awaiting insurer"),
                            ("settled", "Settled"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("vehicle_registration", models.CharField(blank=True, max_length=20)),
                ("vehicle_make_model", models.CharField(blank=True, max_length=100)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=30)),
                ("driver_email", models.EmailField(blank=True, max_length=254)),
                ("accident_date", models.DateField(blank=True, null=True)),
                ("accident_time", models.TimeField(blank=True, null=True)),
                ("accident_location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("police_report_number", models.CharField(blank=True, max_length=50)),
                (
                    "fault",
                    models.CharField(
                        choices=[
                            ("unknown", "Not yet determined"),
                            ("our_driver", "Our driver at fault"),
                            ("third_party", "Third party at fault"),
                            ("shared", "Shared / knock for knock"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("third_party_name", models.CharField(blank=True, max_length=100)),
                ("third_party_phone", models.CharField(blank=True, max_length=30)),
                ("third_party_vehicle", models.CharField(blank=True, max_length=100)),
                ("third_party_insurer", models.CharField(blank=True, max_length=100)),
                ("insurer", models.CharField(blank=True, max_length=100)),
                ("policy_number", models.CharField(blank=True, max_length=50)),
                (
                    "excess_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("drive_folder_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("towing", "Towing"),
                            ("survey", "Survey fee"),
                            ("excess", "Excess"),
                            ("legal", "Legal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("written_off", "Written off"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_items",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccidentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(blank=True, max_length=100)),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("web_view_link", models.URLField(blank=True)),
                ("local_file", models.FileField(blank=True, upload_to="photos/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Received"), ("out", "Sent")], max_length=3
                    ),
                ),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("gmail_message_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="claims.claim",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalClaim",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("awaiting_survey", "Awaiting survey"),
                            ("awaiting_insurer", "Awaiting insurer"),
                            ("settled", "Settled"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("vehicle_registration", models.CharField(blank=True, max_length=20)),
                ("vehicle_make_model", models.CharField(blank=True, max_length=100)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=30)),
                ("driver_email", models.EmailField(blank=True, max_length=254)),
                ("accident_date", models.DateField(blank=True, null=True)),
                ("accident_time", models.TimeField(blank=True, null=True)),
                ("accident_location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("police_report_number", models.CharField(blank=True, max_length=50)),
                (
                    "fault",
                    models.CharField(
                        choices=[
                            ("unknown", "Not yet determined"),
                            ("our_driver", "Our driver at fault"),
                            ("third_party", "Third party at fault"),
                            ("shared", "Shared / knock for knock"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("third_party_name", models.CharField(blank=True, max_length=100)),
                ("third_party_phone", models.CharField(blank=True, max_length=30)),
                ("third_party_vehicle", models.CharField(blank=True, max_length=100)),
                ("third_party_insurer", models.CharField(blank=True, max_length=100)),
                ("insurer", models.CharField(blank=True, max_length=100)),
                ("policy_number", models.CharField(blank=True, max_length=50)),
                (
                    "excess_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("drive_folder_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical claim",
                "verbose_name_plural": "historical claims",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at", "due_at"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surveyor_name", models.CharField(max_length=100)),
                ("surveyor_company", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("report_drive_file_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
