# Generated by Django 5.2.16 on 2026-07-09 20:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.CharField(max_length=20, unique=True)),
                ("make_model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "No longer in fleet"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("acquired_on", models.DateField(blank=True, null=True)),
                ("retired_on", models.DateField(blank=True, null=True)),
                (
                    "vrt_due",
                    models.DateField(blank=True, null=True, verbose_name="VRT due"),
                ),
                (
                    "licence_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Road licence due"
                    ),
                ),
                (
                    "insurance_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Insurance renewal"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["registration"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVehicle",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("registration", models.CharField(db_index=True, max_length=20)),
                ("make_model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "No longer in fleet"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("acquired_on", models.DateField(blank=True, null=True)),
                ("retired_on", models.DateField(blank=True, null=True)),
                (
                    "vrt_due",
                    models.DateField(blank=True, null=True, verbose_name="VRT due"),
                ),
                (
                    "licence_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Road licence due"
                    ),
                ),
                (
                    "insurance_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Insurance renewal"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vehicle",
                "verbose_name_plural": "historical vehicles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
