# Generated by Django 5.2.16 on 2026-07-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_vehicle_historicalvehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvehicle",
            name="licence_due",
        ),
        migrations.RemoveField(
            model_name="historicalvehicle",
            name="vrt_due",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="licence_due",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vrt_due",
        ),
    ]
