# Generated by Django 5.2.16 on 2026-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_remove_historicalvehicle_licence_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Amount paid",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="bills_sent_on",
            field=models.DateField(blank=True, null=True, verbose_name="Bills sent"),
        ),
        migrations.AddField(
            model_name="claim",
            name="chase_on",
            field=models.DateField(blank=True, null=True, verbose_name="Chase on"),
        ),
        migrations.AddField(
            model_name="claim",
            name="drivable",
            field=models.BooleanField(blank=True, null=True, verbose_name="Drivable?"),
        ),
        migrations.AddField(
            model_name="claim",
            name="estimate_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Estimate claim amt",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="insurer_claim_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Our insurer claim no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Invoice no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="labour_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Labour (net)",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="loe_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="LOE daily amount",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="loe_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="LOE days"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="next_action",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Claim phase / next action"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="offset_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Offset",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="others_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Others",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="parts_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Parts",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etars", "ETARS"),
                    ("f2r", "F2R (front to rear)"),
                    ("rar", "RAR (police report)"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="settlement_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Settlement",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="spray_material_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Spray + material (net)",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="survey_in_hand",
            field=models.BooleanField(default=False, verbose_name="Survey in hand?"),
        ),
        migrations.AddField(
            model_name="claim",
            name="third_party_owner_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP owner name"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="third_party_owner_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP owner contact no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="third_party_registration",
            field=models.CharField(blank=True, max_length=20, verbose_name="TP reg no"),
        ),
        migrations.AddField(
            model_name="claim",
            name="tp2_insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP2 insurance"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tp2_owner_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP2 owner name"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tp2_owner_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP2 contact no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tp2_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP2 reg no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="tp_claim_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="TP claim no"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Amount paid",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="bills_sent_on",
            field=models.DateField(blank=True, null=True, verbose_name="Bills sent"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="chase_on",
            field=models.DateField(blank=True, null=True, verbose_name="Chase on"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="drivable",
            field=models.BooleanField(blank=True, null=True, verbose_name="Drivable?"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="estimate_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Estimate claim amt",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="insurer_claim_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Our insurer claim no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Invoice no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="labour_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Labour (net)",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="loe_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="LOE daily amount",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="loe_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="LOE days"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="next_action",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Claim phase / next action"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="offset_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Offset",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="others_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Others",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="parts_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Parts",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etars", "ETARS"),
                    ("f2r", "F2R (front to rear)"),
                    ("rar", "RAR (police report)"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="settlement_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Settlement",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="spray_material_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Spray + material (net)",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="survey_in_hand",
            field=models.BooleanField(default=False, verbose_name="Survey in hand?"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="third_party_owner_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP owner name"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="third_party_owner_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP owner contact no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="third_party_registration",
            field=models.CharField(blank=True, max_length=20, verbose_name="TP reg no"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="tp2_insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP2 insurance"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="tp2_owner_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP2 owner name"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="tp2_owner_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP2 contact no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="tp2_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP2 reg no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="tp_claim_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="TP claim no"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="claim",
            name="fault",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet determined"),
                    ("our_driver", "Our insured (OI) at fault"),
                    ("third_party", "Third party (TP) at fault"),
                    ("shared", "Shared / knock for knock"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Fault (OI / TP)",
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Our insurer"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="police_report_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Report reference no"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="third_party_insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP insurance"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="third_party_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP driver name"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="third_party_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP driver contact no"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="third_party_vehicle",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP vehicle make"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="fault",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet determined"),
                    ("our_driver", "Our insured (OI) at fault"),
                    ("third_party", "Third party (TP) at fault"),
                    ("shared", "Shared / knock for knock"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Fault (OI / TP)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Our insurer"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="police_report_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Report reference no"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="third_party_insurer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP insurance"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="third_party_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP driver name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="third_party_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="TP driver contact no"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="third_party_vehicle",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="TP vehicle make"
            ),
        ),
    ]
