# Generated by Django 5.2.16 on 2026-07-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "claims",
            "0004_claim_amount_paid_claim_bills_sent_on_claim_chase_on_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="auto_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="claims.claim",
            ),
        ),
    ]
