# Generated by Django 5.2.16 on 2026-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0005_reminder_auto_key_reminder_is_auto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="case_number",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="case_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
