# Generated by Django 5.2.16 on 2026-07-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_claim_case_number_historicalclaim_case_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="driver_email",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="driver_phone",
        ),
        migrations.RemoveField(
            model_name="historicalclaim",
            name="driver_email",
        ),
        migrations.RemoveField(
            model_name="historicalclaim",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="historicalclaim",
            name="driver_phone",
        ),
    ]
