# Generated by Django 5.2.16 on 2026-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0007_remove_claim_driver_email_remove_claim_driver_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="third_party_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP number plate"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="tp2_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP2 number plate"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="third_party_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP number plate"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="tp2_registration",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="TP2 number plate"
            ),
        ),
    ]
