# Generated by Django 5.2.16 on 2026-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0008_alter_claim_third_party_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "address",
                    models.TextField(help_text="Full postal address, one line each"),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.CharField(blank=True, max_length=120)),
                ("website", models.CharField(blank=True, max_length=120)),
                (
                    "vat_no",
                    models.CharField(blank=True, max_length=40, verbose_name="VAT no"),
                ),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                ("iban", models.CharField(blank=True, max_length=60)),
                ("account_no", models.CharField(blank=True, max_length=40)),
                ("swift", models.CharField(blank=True, max_length=20)),
                (
                    "logo_static",
                    models.CharField(
                        blank=True,
                        help_text="Path under static/, e.g. img/companies/vai.png",
                        max_length=120,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="company_logos/")),
                ("footer_note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["order", "name"],
            },
        ),
    ]
