# Generated by Django 5.2.16 on 2026-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0010_othercharge"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Daily amount"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
