# Generated by Django 5.2.16 on 2026-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0011_dailyrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="insurer_contact",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Chase — who & contact details"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="liability",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet decided"),
                    ("accepted", "Accepted (Yes)"),
                    ("disputed", "Disputed (No)"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="Liability accepted?",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="liability_chase_date",
            field=models.DateField(
                blank=True,
                help_text="Optional manual date; otherwise chased monthly",
                null=True,
                verbose_name="Liability chase date",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="survey_booked",
            field=models.BooleanField(default=False, verbose_name="Survey booked?"),
        ),
        migrations.AddField(
            model_name="claim",
            name="survey_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="insurer_contact",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Chase — who & contact details"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="liability",
            field=models.CharField(
                choices=[
                    ("unknown", "Not yet decided"),
                    ("accepted", "Accepted (Yes)"),
                    ("disputed", "Disputed (No)"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="Liability accepted?",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="liability_chase_date",
            field=models.DateField(
                blank=True,
                help_text="Optional manual date; otherwise chased monthly",
                null=True,
                verbose_name="Liability chase date",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="survey_booked",
            field=models.BooleanField(default=False, verbose_name="Survey booked?"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="survey_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="claim",
            name="survey_in_hand",
            field=models.BooleanField(default=False, verbose_name="Survey received?"),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="survey_in_hand",
            field=models.BooleanField(default=False, verbose_name="Survey received?"),
        ),
    ]
