# Generated by Django 5.2.16 on 2026-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0012_claim_insurer_contact_claim_liability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="exo_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="EXO number"
            ),
        ),
    ]
