# Generated by Django 5.2.16 on 2026-07-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0013_company_exo_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="insurer_email",
            field=models.EmailField(
                blank=True,
                help_text="Where chase/recovery emails are sent for this claim",
                max_length=254,
                verbose_name="Insurer email",
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="insurer_email",
            field=models.EmailField(
                blank=True,
                help_text="Where chase/recovery emails are sent for this claim",
                max_length=254,
                verbose_name="Insurer email",
            ),
        ),
    ]
