# Generated by Django 5.2.16 on 2026-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0014_claim_insurer_email_historicalclaim_insurer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="awaiting_from",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Awaiting from"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="details",
            field=models.CharField(blank=True, max_length=255, verbose_name="Details"),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="awaiting_from",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Awaiting from"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="details",
            field=models.CharField(blank=True, max_length=255, verbose_name="Details"),
        ),
    ]
