# Generated by Django 5.2.16 on 2026-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0017_seed_repair_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Our driver name"
            ),
        ),
        migrations.AddField(
            model_name="historicalclaim",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Our driver name"
            ),
        ),
    ]
