# Generated by Django 5.2.16 on 2026-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0019_repairline"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "garage",
                    models.CharField(
                        choices=[("acl", "ACL Garage")],
                        db_index=True,
                        default="acl",
                        max_length=20,
                    ),
                ),
                (
                    "accident_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Accident date"
                    ),
                ),
                (
                    "survey_date",
                    models.DateField(blank=True, null=True, verbose_name="Survey date"),
                ),
                (
                    "plate_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="No plate"
                    ),
                ),
                (
                    "client",
                    models.CharField(blank=True, max_length=200, verbose_name="Client"),
                ),
                (
                    "make",
                    models.CharField(blank=True, max_length=120, verbose_name="Make"),
                ),
                (
                    "claim_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Claim No"
                    ),
                ),
                (
                    "surveyor",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Surveyor"
                    ),
                ),
                (
                    "insurance",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Insurance"
                    ),
                ),
                (
                    "report_received",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Report received"
                    ),
                ),
                (
                    "go_ahead",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Go ahead?"
                    ),
                ),
                ("is_closed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-accident_date", "-id"],
            },
        ),
    ]
