# Generated by Django 5.2.16 on 2026-07-23 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0023_create_garage_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(
                        default="ACR Garage", max_length=120, verbose_name="Garage name"
                    ),
                ),
                (
                    "payable_to",
                    models.CharField(
                        default="Mario Galea", max_length=120, verbose_name="Payable to"
                    ),
                ),
                (
                    "issuer_contact",
                    models.CharField(
                        default="9946 8105",
                        max_length=120,
                        verbose_name="Contact details",
                    ),
                ),
                (
                    "issuer_vat",
                    models.CharField(
                        default="1579 7311 MT", max_length=60, verbose_name="VAT No"
                    ),
                ),
                (
                    "issuer_email",
                    models.EmailField(
                        default="acrgarage@gmail.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Invoice No"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Invoice date"
                    ),
                ),
                (
                    "bill_to",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Bill to"
                    ),
                ),
                (
                    "bill_contact_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Contact name"
                    ),
                ),
                (
                    "bill_company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Client company name"
                    ),
                ),
                ("bill_address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "bill_email",
                    models.CharField(blank=True, max_length=200, verbose_name="Email"),
                ),
                (
                    "bill_vat",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Client VAT"
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="VAT rate %",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, verbose_name="Remarks / payment instructions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edited by",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GarageInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_date",
                    models.DateField(blank=True, null=True, verbose_name="Date"),
                ),
                (
                    "reg_no",
                    models.CharField(blank=True, max_length=20, verbose_name="Reg No"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Unit price",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="claims.garageinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
