# Generated by Django 5.2.16 on 2026-07-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0024_garageinvoice_garageinvoiceline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_acc",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of accident"
                    ),
                ),
                (
                    "our_reg",
                    models.CharField(blank=True, max_length=20, verbose_name="Our Reg"),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Driver name"
                    ),
                ),
                (
                    "tp_reg",
                    models.CharField(blank=True, max_length=20, verbose_name="TP Reg"),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Vehicle make"
                    ),
                ),
                (
                    "tp_driver_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="TP driver name"
                    ),
                ),
                (
                    "contact_details",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Contact details"
                    ),
                ),
                (
                    "tp_owner_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="TP owner name"
                    ),
                ),
                (
                    "tp_owner_contact",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="TP owner contact no"
                    ),
                ),
                (
                    "tp_insurance",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="TP insurance"
                    ),
                ),
                (
                    "other_tps",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Other TPs"
                    ),
                ),
                (
                    "tp2_owner_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="TP2 owner name"
                    ),
                ),
                (
                    "tp2_contact",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="TP2 contact no"
                    ),
                ),
                (
                    "tp2_insurance",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="TP2 insurance"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Report type"
                    ),
                ),
                (
                    "fault",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Fault (OI / TP)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_of_acc", "-id"],
                "indexes": [
                    models.Index(
                        fields=["our_reg"], name="claims_acci_our_reg_bb8738_idx"
                    ),
                    models.Index(
                        fields=["tp_reg"], name="claims_acci_tp_reg_55f721_idx"
                    ),
                ],
            },
        ),
    ]
