# Generated by Django 5.2.16 on 2026-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0025_accidentrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garagejob",
            name="garage",
            field=models.CharField(
                choices=[("acl", "ACR Garage")],
                db_index=True,
                default="acl",
                max_length=20,
            ),
        ),
    ]
