# Generated by Django 5.2.16 on 2026-07-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0026_alter_garagejob_garage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        db_index=True,
                        default="Firefly",
                        max_length=60,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "claim_date",
                    models.DateField(blank=True, null=True, verbose_name="Date"),
                ),
                (
                    "our_reg",
                    models.CharField(blank=True, max_length=20, verbose_name="Our Reg"),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Driver name"
                    ),
                ),
                (
                    "tp_reg",
                    models.CharField(blank=True, max_length=20, verbose_name="TP Reg"),
                ),
                (
                    "vehicle_make",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Vehicle make"
                    ),
                ),
                (
                    "insurer",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Insurer"
                    ),
                ),
                (
                    "claim_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Claim No"
                    ),
                ),
                (
                    "fault",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Fault (OI / TP)"
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Details"
                    ),
                ),
                (
                    "status_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Status / awaiting"
                    ),
                ),
                (
                    "estimate_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Estimate (€)",
                    ),
                ),
                ("is_closed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edited by",
                    ),
                ),
            ],
            options={
                "ordering": ["-claim_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["our_reg"], name="claims_gene_our_reg_af46f4_idx"
                    ),
                    models.Index(
                        fields=["tp_reg"], name="claims_gene_tp_reg_976fa0_idx"
                    ),
                ],
            },
        ),
    ]
