# Generated by Django 5.2.16 on 2026-07-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0028_garagejobitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageJobLabour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="Work"),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="Hours"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Rate €/hr",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour",
                        to="claims.garagejob",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
