# Generated by Django 5.2.16 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0030_garageinvoice_for_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="garagejobitem",
            name="details",
            field=models.CharField(blank=True, max_length=255, verbose_name="Details"),
        ),
    ]
