# Generated by Django 5.2.16 on 2026-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0031_garagejobitem_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="garagejob",
            name="for_kind",
            field=models.CharField(
                choices=[
                    ("group", "Vai Drive (Francis)"),
                    ("personal", "My own garage"),
                ],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Job for",
            ),
        ),
    ]
