# Generated by Django 5.2.16 on 2026-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0032_garagejob_for_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garageinvoice",
            name="for_kind",
            field=models.CharField(
                choices=[
                    ("group", "Vai Drive (Frances)"),
                    ("personal", "My own garage"),
                ],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Invoice for",
            ),
        ),
        migrations.AlterField(
            model_name="garagejob",
            name="for_kind",
            field=models.CharField(
                choices=[
                    ("group", "Vai Drive (Frances)"),
                    ("personal", "My own garage"),
                ],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Job for",
            ),
        ),
    ]
