# Generated by Django 5.2.16 on 2026-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0033_alter_garageinvoice_for_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "claim statuses",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("awaiting_survey", "Awaiting survey"),
                    ("awaiting_insurer", "Awaiting insurer"),
                    ("settled", "Settled"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("awaiting_survey", "Awaiting survey"),
                    ("awaiting_insurer", "Awaiting insurer"),
                    ("settled", "Settled"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=40,
            ),
        ),
    ]
