# Generated by Django 5.2.16 on 2026-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0034_claimstatus_alter_claim_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvehicle",
            name="insurance_due",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="insurance_due",
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="additional_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Additional costs (€)",
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="insurance_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Insurance amount (€)",
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="licence_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Licence amount (€)",
            ),
        ),
        migrations.AddField(
            model_name="historicalvehicle",
            name="pay_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Insurance pay date"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="additional_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Additional costs (€)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="insurance_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Insurance amount (€)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="licence_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Licence amount (€)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="pay_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Insurance pay date"
            ),
        ),
    ]
