# Generated by Django 5.2.16 on 2026-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0035_remove_historicalvehicle_insurance_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvehicle",
            name="owner",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, verbose_name="Owner"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, verbose_name="Owner"
            ),
        ),
    ]
