# Generated by Django 5.2.16 on 2026-07-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0037_vehicle_yearly_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="garagejob",
            name="model",
            field=models.CharField(blank=True, max_length=120, verbose_name="Model"),
        ),
    ]
