# Generated by Django 5.2.16 on 2026-07-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0039_vehicle_additional_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garageinvoice",
            name="for_kind",
            field=models.CharField(
                choices=[("group", "Vai Drive"), ("personal", "My own garage")],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Invoice for",
            ),
        ),
        migrations.AlterField(
            model_name="garagejob",
            name="for_kind",
            field=models.CharField(
                choices=[("group", "Vai Drive"), ("personal", "My own garage")],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Job for",
            ),
        ),
    ]
