# Generated by Django 5.2.16 on 2026-07-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0040_alter_garageinvoice_for_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurer", models.CharField(max_length=120)),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paid", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_claims",
                        to="claims.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_paid", "-id"],
            },
        ),
    ]
