# Generated by Django 5.2.16 on 2026-08-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0040_alter_garageinvoice_for_kind_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInsurer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Client name")),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="One line each", verbose_name="Address"
                    ),
                ),
                (
                    "customer_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Bill-to Customer No."
                    ),
                ),
                (
                    "vat_reg_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="VAT Registration No."
                    ),
                ),
                (
                    "company_reg_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Company Reg. No."
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=200, verbose_name="Email"),
                ),
                (
                    "default_payment_terms",
                    models.CharField(
                        blank=True,
                        default="Net 15 days",
                        max_length=60,
                        verbose_name="Payment Terms",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(
                        default="eCabs Operators Company Ltd.",
                        max_length=160,
                        verbose_name="Issuer name",
                    ),
                ),
                (
                    "issuer_address",
                    models.TextField(
                        default="eCabs Head Office\nTriq Santu Wistin\nSTJ 3180 San Giljan\nMalta",
                        verbose_name="Issuer address",
                    ),
                ),
                (
                    "issuer_email",
                    models.CharField(
                        default="finance@ecabs.com.mt",
                        max_length=200,
                        verbose_name="Email",
                    ),
                ),
                (
                    "issuer_website",
                    models.CharField(
                        default="https://www.ecabs.com.mt/",
                        max_length=200,
                        verbose_name="Home Page",
                    ),
                ),
                (
                    "issuer_phone",
                    models.CharField(
                        default="21383838", max_length=60, verbose_name="Phone No."
                    ),
                ),
                (
                    "issuer_vat",
                    models.CharField(
                        default="MT21583611",
                        max_length=60,
                        verbose_name="VAT Registration No.",
                    ),
                ),
                (
                    "issuer_exo",
                    models.CharField(
                        default="4270", max_length=40, verbose_name="EXO Number"
                    ),
                ),
                (
                    "bill_to_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Bill-to name"
                    ),
                ),
                (
                    "bill_to_address",
                    models.TextField(blank=True, verbose_name="Bill-to address"),
                ),
                (
                    "bill_customer_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Bill-to Customer No."
                    ),
                ),
                (
                    "bill_vat_reg_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="VAT Registration No."
                    ),
                ),
                (
                    "bill_company_reg_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Company Reg. No."
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Invoice No."
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Document Date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        default="Net 15 days",
                        max_length=60,
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="VAT rate %",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoices",
                        to="claims.claim",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="claims.clientinsurer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edited by",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "original_amount_incl_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Original Amount Incl. VAT",
                    ),
                ),
                (
                    "discount_amount_incl_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount incl. VAT",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="claims.salesinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
