# Generated by Django 5.2.17 on 2026-09-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0041_insuranceclaim"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
