# Generated by Django 5.2.16 on 2026-08-08 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0041_clientinsurer_salesinvoice_salesinvoiceline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(
                        default="eCabs Operators Company Ltd.",
                        max_length=160,
                        verbose_name="Issuer name",
                    ),
                ),
                (
                    "issuer_address",
                    models.TextField(
                        default="eCabs Head Office\nTriq Santu Wistin\nSTJ 3180 San Giljan\nMalta",
                        verbose_name="Issuer address",
                    ),
                ),
                (
                    "issuer_email",
                    models.CharField(
                        default="finance@ecabs.com.mt",
                        max_length=200,
                        verbose_name="Email",
                    ),
                ),
                (
                    "issuer_website",
                    models.CharField(
                        default="https://www.ecabs.com.mt/",
                        max_length=200,
                        verbose_name="Home Page",
                    ),
                ),
                (
                    "issuer_phone",
                    models.CharField(
                        default="21383838", max_length=60, verbose_name="Phone No."
                    ),
                ),
                (
                    "issuer_vat",
                    models.CharField(
                        default="MT21583611",
                        max_length=60,
                        verbose_name="VAT Registration No.",
                    ),
                ),
                (
                    "issuer_exo",
                    models.CharField(
                        default="4270", max_length=40, verbose_name="EXO Number"
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Receipt No."
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Receipt Date"
                    ),
                ),
                (
                    "vehicle_reg",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vehicle reg"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Supplier"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Reference"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="VAT rate %",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts_receipts",
                        to="claims.claim",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edited by",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PartsReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_code",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Part code"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Qty"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Unit price",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="claims.partsreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
