# Generated by Django 5.2.16 on 2026-08-08 06:21

from django.db import migrations, models

OLD = "finance@ecabs.com.mt"
NEW = "motorclaims@ecabs.com.mt"


def set_new_email(apps, schema_editor):
    for name in ("SalesInvoice", "PartsReceipt"):
        model = apps.get_model("claims", name)
        model.objects.filter(issuer_email=OLD).update(issuer_email=NEW)


def revert_email(apps, schema_editor):
    for name in ("SalesInvoice", "PartsReceipt"):
        model = apps.get_model("claims", name)
        model.objects.filter(issuer_email=NEW).update(issuer_email=OLD)


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0042_partsreceipt_partsreceiptline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partsreceipt",
            name="issuer_email",
            field=models.CharField(
                default="motorclaims@ecabs.com.mt", max_length=200, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="issuer_email",
            field=models.CharField(
                default="motorclaims@ecabs.com.mt", max_length=200, verbose_name="Email"
            ),
        ),
        migrations.RunPython(set_new_email, revert_email),
    ]
