# Generated by Django 5.2.16 on 2026-08-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0043_alter_partsreceipt_issuer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimExtraStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=40)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_statuses",
                        to="claims.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
                "unique_together": {("claim", "slug")},
            },
        ),
    ]
