# Generated by Django 5.2.16 on 2026-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0044_claimextrastatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="garageinvoice",
            name="issuer_iban",
            field=models.CharField(
                default="MT90VALL22013000000040019330200",
                max_length=40,
                verbose_name="IBAN",
            ),
        ),
        migrations.AddField(
            model_name="garageinvoice",
            name="vehicle_reg",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Registration No"
            ),
        ),
    ]
