# Generated by Django 5.2.16 on 2026-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0045_garageinvoice_issuer_iban_garageinvoice_vehicle_reg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garageinvoice",
            name="for_kind",
            field=models.CharField(
                choices=[("group", "Fast drop"), ("personal", "My own garage")],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Invoice for",
            ),
        ),
        migrations.AlterField(
            model_name="garagejob",
            name="for_kind",
            field=models.CharField(
                choices=[("group", "Fast drop"), ("personal", "My own garage")],
                db_index=True,
                default="group",
                max_length=10,
                verbose_name="Job for",
            ),
        ),
    ]
