# Generated by Django 5.2.16 on 2026-08-15 19:45

from django.conf import settings
from django.db import migrations, models


def dedupe_numbers(apps, schema_editor):
    """Make existing document numbers unique before the constraints go on.

    Numbers used to be handed out as "highest on file plus one", which could
    repeat once a document was deleted. Any duplicate already saved keeps the
    number on the oldest row; the later ones get a -2, -3 … suffix so nothing
    is lost and the unique constraints can be applied.
    """
    for model_name, field in (
        ("GarageInvoice", "invoice_no"),
        ("SalesInvoice", "invoice_no"),
        ("PartsReceipt", "receipt_no"),
    ):
        model = apps.get_model("claims", model_name)
        seen = set()
        for row in model.objects.order_by("id").iterator():
            value = getattr(row, field) or ""
            if not value or value not in seen:
                if value:
                    seen.add(value)
                continue
            suffix = 2
            while f"{value}-{suffix}" in seen:
                suffix += 1
            new_value = f"{value}-{suffix}"[:40]
            setattr(row, field, new_value)
            row.save(update_fields=[field])
            seen.add(new_value)


def noop(apps, schema_editor):
    """Renamed duplicates stay as they are — they are real documents now."""


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0046_alter_garageinvoice_for_kind_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_numbers, noop),
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.AddConstraint(
            model_name="garageinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_no", ""), _negated=True),
                fields=("invoice_no",),
                name="unique_garage_invoice_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="partsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_no", ""), _negated=True),
                fields=("receipt_no",),
                name="unique_parts_receipt_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_no", ""), _negated=True),
                fields=("invoice_no",),
                name="unique_sales_invoice_no",
            ),
        ),
    ]
