# Generated by Django 5.2.16 on 2026-08-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0047_numbersequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclecost",
            name="insurance_refund",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Refund received if the insurance was cancelled",
                max_digits=10,
                null=True,
                verbose_name="Insurance refund (€)",
            ),
        ),
        migrations.AddField(
            model_name="vehiclecost",
            name="refund_date",
            field=models.DateField(blank=True, null=True, verbose_name="Refund date"),
        ),
    ]
