# Generated by Django 5.2.16 on 2026-08-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0048_vehiclecost_insurance_refund_vehiclecost_refund_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="garageinvoice",
            name="claim_no",
            field=models.CharField(blank=True, max_length=60, verbose_name="Claim No"),
        ),
    ]
