# Generated by Django 5.2.16 on 2026-08-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0049_garageinvoice_claim_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="garageinvoice",
            name="vehicle_make_model",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Make / model"
            ),
        ),
    ]
