from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("overview/", views.overview, name="overview"),
    path("claims/", views.claim_list, name="claim_list"),
    path("claims/group/<slug:group>/", views.claim_group, name="claim_group"),
    path("claims/<int:pk>/estimate/", views.claim_set_estimate, name="claim_set_estimate"),
    path("claims/at-fault/", views.claims_at_fault, name="claims_at_fault"),
    path("claims/<int:pk>/at-fault-update/", views.at_fault_update, name="at_fault_update"),
    path("claims/master/", views.master_sheet, name="master_sheet"),
    path("claims/master/csv/", views.master_sheet_csv, name="master_sheet_csv"),
    path("claims/bills/", views.bills_report, name="bills_report"),
    path("data/", views.data_dashboard, name="data_dashboard"),
    path("audit/", views.audit_trail, name="audit_trail"),
    path("maintenance/", views.maintenance, name="maintenance"),
    path("maintenance/rate/<int:pk>/edit/", views.rate_edit, name="rate_edit"),
    path("maintenance/rate/<int:pk>/delete/", views.rate_delete, name="rate_delete"),
    path("add/<slug:kind>/", views.record_add, name="record_add"),
    path("claims/new/", views.claim_new, name="claim_new"),
    path("claims/<int:pk>/", views.claim_detail, name="claim_detail"),
    path("claims/<int:pk>/tab/<slug:tab>/", views.claim_detail, name="claim_tab"),
    path("claims/<int:pk>/edit/", views.claim_edit, name="claim_edit"),
    path("claims/<int:pk>/autosave/", views.claim_autosave, name="claim_autosave"),
    path("claims/<int:pk>/submit/", views.claim_submit, name="claim_submit"),
    path("claims/<int:pk>/status/", views.claim_set_status, name="claim_set_status"),
    path("claims/<int:pk>/documents/", views.claim_documents, name="claim_documents"),
    path("claims/<int:pk>/invoice.pdf", views.claim_invoice_pdf, name="claim_invoice_pdf"),
    path("claims/<int:pk>/lou.pdf", views.claim_lou_pdf, name="claim_lou_pdf"),
    path("claims/<int:pk>/repairs.pdf", views.claim_repairs_pdf, name="claim_repairs_pdf"),
    path("claims/<int:pk>/repair-lines/", views.claim_set_repair_lines, name="claim_set_repair_lines"),
    path("claims/<int:pk>/repair-type/add/", views.repair_type_add, name="repair_type_add"),
    path("claims/<int:pk>/photos/upload/", views.photo_upload, name="photo_upload"),
    path("claims/<int:pk>/surveys/add/", views.survey_add, name="survey_add"),
    path("claims/<int:pk>/emails/add/", views.email_add, name="email_add"),
    path("claims/<int:pk>/emails/send/", views.email_send, name="email_send"),
    path("claims/<int:pk>/reminders/add/", views.reminder_add, name="reminder_add"),
    path("claims/<int:pk>/billing/add/", views.billing_add, name="billing_add"),
    path("vehicles/", views.vehicle_list, name="vehicle_list"),
    path("vehicles/add/", views.vehicle_add, name="vehicle_add"),
    path("vehicles/<int:pk>/", views.vehicle_edit, name="vehicle_edit"),
    path("vehicles/<int:pk>/toggle/", views.vehicle_toggle_status, name="vehicle_toggle_status"),
    path("vehicles/<int:pk>/delete/", views.vehicle_delete, name="vehicle_delete"),
    path("reminders/", views.reminder_list, name="reminder_list"),
    path("reminders/add/", views.reminder_create, name="reminder_create"),
    path("reminders/<int:pk>/toggle/", views.reminder_toggle, name="reminder_toggle"),
]
